name: onestop
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # TODO freeze all versions before release
  - matplotlib
  - numpy
  - seaborn
  - pandas
  - datasets
  - plotly
  - scipy
  - ipykernel
  - dropbox # TODO remove?
  - ipywidgets
  # - loguru
  - openpyxl
  - statsmodels
  # - pyyaml
  - pytorch
  - pytorch-cuda=12.4
  - jupyter
  - transformers
  - spacy
  - pip
  - pip:
    - juliacall
    - git+https://github.com/lacclab/text-metrics.git@v1.1.3
    - typed-argument-parser
    - -e . # for development
