name: onestop
channels:
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - seaborn
  - pandas
  - datasets
  - plotly
  - scipy
  # - sphinx
  # - mypy
  - ipykernel
  - dropbox
  - ipywidgets
  - pip
  - loguru
  - pip:
    - juliacall
    - -e . # for development
    # - myst-parser
    # - sphinx-book-theme
    # - sphinx-autobuild