# TODO freeze version before release
name: onestop
channels:
  - pytorch
  - huggingface
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - seaborn
  - pandas
  - datasets
  - plotly
  - scipy
  - ipykernel
  - dropbox # TODO remove
  - ipywidgets
  # - loguru
  - openpyxl
  - statsmodels
  # - pyyaml
  - cuda-toolkit
  - pytorch-cuda
  - pytorch
  - jupyter
  - transformers
  - spacy
  - pip
  - pip:
    - juliacall
    - git+https://github.com/lacclab/text-metrics.git #@v1.1.2
    - typed-argument-parser
    - -e . # for development
