name: onestop
channels:
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - seaborn
  - pandas
  - datasets
  # - sphinx
  # - mypy
  - ipykernel
  - pip
  # - pip:
    # - myst-parser
    # - sphinx-book-theme
    # - sphinx-autobuild